### ISSUE TITLE
[ragel] compiler warnings on some 64-bit Windows (Ragel 6.5)

### ISSUE THREAD

**Issue by adriandt** [adriandt/ragel#35]
reported by Dave McCaldon

<pre>
ip_addr_parser.c(442) : warning C4244: '+=' : conversion from '__int64' to 'unsigned int', possible loss of data _trans += (_mid - _keys);
ip_addr_parser.c(465) : warning C4244: '+=' : conversion from '__int64' to 'unsigned int', possible loss of data _trans += ((_mid - _keys)>>1);
</pre>

**Comment by loveJasmine** [comment]
how to compile and install ragel on windows 10
